services:
  guest-cursor:
    build: .
    ports:
      - "7171:7171"
    restart: unless-stopped

    healthcheck:
      test: curl --fail http://localhost:7171/cursor || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
